package com.ecom.core.dto;
// default package
// Generated 15 Sep, 2019 5:40:40 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * UserMaster generated by hbm2java
 */
@Entity
/* @Table(name="customers",catalog = "ecommerce") */
@Table
public class Customers implements java.io.Serializable {

	private Long id;
	private String name;
	private String lastName;
	private String address;
	private String landmark;
	private String mobileNumber;
	private String emailId;
	private String city;
	private String state;
	private String country;
	private String pinCode;
	private String password;
	private String otp;
	private String deviceId;
	private String os;
	private String isAdmin="false";
	private String isGuest="false";
	private String isActive="true";
    private String birthday;
	
	
	public Customers() {
	}

	


	public Customers(Long id, String name, String lastName, String address, String landmark, String mobileNumber,
			String emailId, String city, String state, String country, String pinCode, String password, String otp,
			String deviceId, String os, String isAdmin, String isGuest, String isActive, String birthday) {
		super();
		this.id = id;
		this.name = name;
		this.lastName = lastName;
		this.address = address;
		this.landmark = landmark;
		this.mobileNumber = mobileNumber;
		this.emailId = emailId;
		this.city = city;
		this.state = state;
		this.country = country;
		this.pinCode = pinCode;
		this.password = password;
		this.otp = otp;
		this.deviceId = deviceId;
		this.os = os;
		this.isAdmin = isAdmin;
		this.isGuest = isGuest;
		this.isActive= isActive;
		this.birthday = birthday;
	}




	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "NAME")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	
	@Column(name = "LAST_NAME")
	public String getLastName() {
		return lastName;
	}

	

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@JsonProperty(access = Access.WRITE_ONLY)
	@Column(name = "PASSWORD")
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@JsonIgnore
	@Column(name = "OTP")
	public String getOtp() {
		return otp;
	}

	public void setOtp(String otp) {
		this.otp = otp;
	}

	@JsonIgnore
	@Column(name = "DEVICE_ID")
	public String getDeviceId() {
		return deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	@JsonIgnore
	@Column(name = "OS")
	public String getOs() {
		return os;
	}

	public void setOs(String os) {
		this.os = os;
	}

	@Column(name = "ADDRESS")
	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}


	@Column(name = "EMAIL_ID")
	public String getEmailId() {
		return emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "MOBILE_NUMBER")
	public String getMobileNumber() {
		return mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	@Column(name = "CITY")
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE")
	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "COUNTRY")
	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "PIN_CODE")
	public String getPinCode() {
		return pinCode;
	}

	public void setPinCode(String pinCode) {
		this.pinCode = pinCode;
	}

	@JsonProperty(access = Access.WRITE_ONLY)
	@Column(name = "IS_ADMIN")
	public String getIsAdmin() {
		return isAdmin;
	}

	public void setIsAdmin(String isAdmin) {
		this.isAdmin = isAdmin;
	}

	@JsonProperty(access = Access.WRITE_ONLY)
	@Column(name="IS_GUEST")
	public String getIsGuest() {
		return isGuest;
	}

	public void setIsGuest(String isGuest) {
		this.isGuest = isGuest;
	}

	@JsonProperty(access = Access.WRITE_ONLY)
	@Column(name="IS_ACTIVE")
	public String getIsActive() {
		return isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	
	@Column(name="LANDMARK")
	public String getLandmark() {
		return landmark;
	}

	public void setLandmark(String landmark) {
		this.landmark = landmark;
	}



	@Column(name = "BIRTHDAY")
	public String getBirthday() {
		return birthday;
	}




	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}
	
	
	
	
	
	
	
}
